name: Gem push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    steps:
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        # Optional, will publish to RubyGems if specified
        api_key: ${{secrets.RUBYGEMS_API_KEY}}